spring:
  application:
    name: spring-security-jwt
  datasource:
    url: jdbc:postgresql://localhost:5435/jwtsecuritydb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    filter:
      order: 0

springdoc:
  swagger-ui:
    url: /openapi.yaml

jwt:
  secret: CiVUWV7amYCNUts6j2SBN+IMDZuVDVKdaf7QlRTIMUk=
  tokenExpiration: 100_000
  refreshTokenExpiration: 1_000_000

server:
  port: 8081