openapi: 3.0.3
info:
  title: "spring-security-jwt API"
  description: "API for spring security with jwt project"
  version: 1.0.0
paths:
  /api/v1/auth/login:
    post:
      summary: "Запрос на аутентификацию пользователя"
      operationId: "login"
      description: "Запрос на аутентификацию пользователя"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        400:
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthException"
  /api/v1/auth/refresh:
    post:
      summary: "Запрос на обновление access и refresh токенов"
      description: "Запрос на обновление access и refresh токенов"
      operationId: "refreshToken"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RefreshTokenRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        400:
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenRefreshNotFoundException"
  /api/v1/auth/register:
    post:
      summary: "Запрос на регистрацию пользователя"
      operationId: "register"
      description: "Запрос на регистрацию пользователя"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        400:
          description: "BAD REQUEST"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthException"
  /api/admin/hello:
    get:
      summary: "Эндпоинт для пользователя с ролью ADMIN"
      operationId: "helloAdmin"
      description: "Эндпоинт для пользователя с ролью ADMIN"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: "FORBIDDEN"
  /api/user/hello:
    get:
      summary: "Эндпоинт для пользователя с ролью USER"
      operationId: "helloUser"
      description: "Эндпоинт для пользователя с ролью USER"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
        400:
          description: "FORBIDDEN"

components:
  schemas:
    TokenResponse:
      type: object
      description: "DTO для возврата токенов"
      properties:
        accessToken:
          type: "string"
        refreshToken:
          type: "string"
    RefreshTokenRequest:
      type: object
      description: "DTO для возврата рефреш токена"
      properties:
        refreshToken:
          type: "string"
    RegisterRequest:
      type: object
      description: "DTO для регистрации"
      properties:
        username:
          type: "string"
        password:
          type: "string"
        email:
          type: "string"
    LoginRequest:
      type: object
      description: "DTO для аутентификации"
      properties:
        username:
          type: "string"
        password:
          type: "string"
    AuthException:
      type: object
      description: "Ошибка аутентификации"
      properties:
        message:
          type: "string"
    TokenRefreshNotFoundException:
      type: object
      description: "Токен не найден"
      properties:
        message:
          type: "string"